DROP TABLE IF EXISTS users, events, categories, locations CASCADE;
CREATE TABLE IF NOT EXISTS users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(250) NOT NULL,
    email varchar(64) NOT NULL,
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT,
    lon FLOAT
);

CREATE TABLE IF NOT EXISTS events (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              varchar(120),
    description        varchar(2000),
    annotation         varchar(2000),
    state              varchar(16),
    category_id        int REFERENCES categories (id) ON DELETE CASCADE,
    created            TIMESTAMP,
    event_date         TIMESTAMP,
    published          TIMESTAMP,
    confirmed_requests int,
    location_id        BIGINT REFERENCES locations (id) ON DELETE CASCADE,
    initiator_id       BIGINT REFERENCES users (id) ON DELETE CASCADE,
    paid               boolean,
    participant_limit  int,
    request_moderation boolean
)